config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :events
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_members, dependent: :destroy
  has_many :members, through: :event_members

  accepts_nested_attributes_for :event_members, allow_destroy: true
  accepts_nested_attributes_for :members

  validates :start, presence: true
  validates :event_date, presence: true
  validates :event_members, presence: true
end

app/models/event_member.rb
class EventMember < ApplicationRecord
  belongs_to :event
  belongs_to :member  

  accepts_nested_attributes_for :event, reject_if: :all_blank
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :event_members, dependent: :destroy
  has_many :events, through: :event_members

  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def escape
    unless session[:is_login]
      flash[:danger] = "権限がありません。ログインしてください。"
      redirect_to root_url
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    escape
    @event = Event.new
    @event.event_date = params["day"]
  end

  # GET /events/1/edit
  def edit
    escape
  end

  # POST /events
  # POST /events.json
  def create
    escape
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        @events = Event.all
        format.html { render :index }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    escape
    respond_to do |format|
      if @event.update(event_params)
        @events = Event.all
        format.html { render :index }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    escape
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:event_date, :start, :end, :color, event_members_attributes: [:id, :member_id, :_destroy])
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    escape
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
    escape
  end

  # POST /members
  # POST /members.json
  def create
    escape
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'メンバーが新しく作られました' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    escape
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'メンバーが更新されました' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    escape
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  require 'openssl'

  PASS_DIGEST = "774fcded1e8ae0bf66bc0bbb9dab74dc1da6387c414b3d64a0cfeebb0d346737"
  PASS_DIGEST.freeze

  def new
  end

  def create
    pass = params[:session][:passcode]
    digest = OpenSSL::Digest.new('sha256')
    digest.update(pass)

    if params[:session][:id] == "sat" && digest.to_s == PASS_DIGEST
      login
      redirect_to root_url
    else
      flash.now[:danger] = "idかパスコードが間違っています"
      render 'new'
    end
  end

  def destroy
    logout
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def event_data
    data = []

    events = Event.includes(:members)
    events.each do |ev|
      element = {}
      element['date'] = ev.event_date.to_s
      if ev.end
        event_time = "#{Tod::TimeOfDay(ev.start).to_s.slice(0, 5)} 〜 #{Tod::TimeOfDay(ev.end).to_s.slice(0, 5)}"
      else
        event_time = "#{Tod::TimeOfDay(ev.start).to_s.slice(0, 5)} 〜 "
      end

      event_member = ""
      ev.members.each do |member|
        event_member += "#{member.name} "
      end
      element['eventTime'] = event_time
      element['eventMember'] = event_member
      element['color'] = ev.color
      data << element
    end
    data
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login
    session[:is_login] = true
  end

  def logout
    session[:is_login] = false
  end
end

app/views/events/_calendar.html.slim
div.text-center
  h1 イベントカレンダー

#calendar

br

sass:
  html, body
    height: 100%
    overflow-y: scroll


javascript:
  var data
  data = #{{ event_data.to_json }}
  isLogin = #{{ session[:is_login] }}
  console.log(data)
  $(document).ready(function(){
    var calendar;
    return calendar = new Calendar('#calendar', data, isLogin);
  });

  // ---
  // generated by coffee-script 1.9.2

app/views/events/_event_member_fields.html.slim
.field.nested-fields
  = f.select :member_id, options_for_select([['—', nil]] + Member.all.order('name').map{|m| [m.name, m.id]}, f.object.event_id)
  = link_to_remove_association '削除', f, class: 'btn btn-default'

app/views/events/_form.html.slim
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      h2 = "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      ul
        - @event.errors.full_messages.each do |message|
          li = message

  p メンバー
  #event_members
    = f.fields_for :event_members do |mem_form|
      = render 'event_member_fields', f: mem_form
    = link_to_add_association 'メンバーを追加', f, :event_members, class: 'btn btn-default'
    = link_to '新規メンバーの作成', :new_member, class: 'btn btn-default'
  .field
    = f.label :event_date, "イベント日時"
    = f.text_field :event_date, class: 'input-group date', id: 'datePicker'
  .field
    = f.label :start, "開始時間"
    = f.text_field :start, class: 'input-group date', id: 'startPicker'
  .field
    = f.label :end, "終了予定時間"
    = f.text_field :end, class: 'input-group date', id: 'endPicker'
  .field
    = f.label :color, "カレンダーに表示する色"
    - choices = [['青', :blue], ['橙', :orange], ['緑', :green], ['黄', :yellow]]
    = f.select :color, choices, selected: :orange

  .actions = f.submit class: 'btn btn-success'

javascript:
  $(function () {
    $('#datePicker').datetimepicker({
      locale: 'ja',
      viewMode: 'days',
      format: 'YYYY/MM/DD'
    });
    $('#startPicker').datetimepicker({
      locale: 'ja',
      viewMode: 'days',
      format: 'HH:mm'
    });
    $('#endPicker').datetimepicker({
      locale: 'ja',
      viewMode: 'days',
      format: 'HH:mm'
    });
  });

app/views/events/_list.html.slim
div.row
  div.col-md-6.col-md-offset-3

    table#events.table.table-striped.table-bordered
      thead
        tr
          th 予定日
          th 時間
          th メンバー
          - if session[:is_login]
            th
            th

      tbody
        - counter = 0
        - data = event_data
        - @events.each do |event|
          tr
            td = data[counter]["date"]
            td = data[counter]["eventTime"]
            td = data[counter]["eventMember"]
            - if session[:is_login]
              td = link_to 'Edit', edit_event_path(event), class:"btn btn-info"
              td = button_to 'Destory', event, method: :delete, class:"btn btn-danger"
            - counter += 1

javascript:
  // デフォルトの設定を変更
  $.extend( $.fn.dataTable.defaults, {
      language: {
          url: "http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Japanese.json"
      }
  });
  $(document).ready(function(){
    console.log($("#events"))
    $("#events").DataTable()
  });

app/views/events/edit.html.slim
div.row
  div.col-md-6.col-md-offset-3
    h1 Editing event

    == render 'form'

    div.text-center
      => link_to 'Show', @event
      '|
      =< link_to 'Back', events_path

app/views/events/index.html.slim
ul.nav.nav-tabs
  li.active
    a href = "#cal-tab" data-toggle = "tab"
      | カレンダー
  li
    a href = "#list-tab" data-toggle = "tab"
      | イベント一覧
.tab-content.shift-down
  #cal-tab.tab-pane.fade.in.active
    = render "calendar"
  #list-tab.tab-pane.fade
    = render "list"

app/views/events/new.html.slim
div.row
  div.col-md-6.col-md-offset-3
    h1 新しいイベントの追加

    == render 'form'

    = link_to 'Back', events_path, class:"btn btn-info"

app/views/events/show.html.slim
div.row
  div.col-md-6.col-md-offset-3
    div.text-center
      h3#notice = notice

      h2
        strong Start:
        = @event.start
      h2
        strong End:
        = @event.end

      =< link_to 'Back', events_path, class: 'btn btn-info'
      '|
      => link_to 'Edit', edit_event_path(@event), class: 'btn btn-info'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | RegisterCalendar
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header.navbar.navbar-fixed-top.navbar-inverse
      .container
        nav
          ul.nav.navbar-nav.navbar-left
            li = link_to "イベント一覧", events_url
            li = link_to "メンバー一覧", members_url
          ul.nav.navbar-nav.navbar-right
            - if(session[:is_login])
              li = link_to "イベント作成", new_event_url
              li = link_to "メンバー作成", new_member_url
              li = link_to logout_path, method: :delete do
                = fa_icon "sign-out", text: "ログアウト"

            - else
              li = link_to login_path do
                = fa_icon "sign-in", text: "ログイン"

    - flash.each do |message_type, message|
      .text-center
        div class=("alert alert-#{message_type}") = message

    .container
      = yield

app/views/members/_form.html.slim
= form_for @member do |f|
  - if @member.errors.any?
    #error_explanation
      h2 = "#{pluralize(@member.errors.count, "error")} prohibited this member from being saved:"
      ul
        - @member.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name, class: 'form-control'

  .actions = f.submit class: 'btn btn-success'

app/views/members/edit.html.slim
div.text-center
  h1 Editing member

== render 'form'

div.text-center
  => link_to 'Show', @member, class: "btn btn-info"
  '|
  =< link_to 'Back', members_path, class: "btn btn-info"

app/views/members/index.html.slim
div.text-center
  h1 メンバー一覧

div.row.scrollable
  div.col-md-6.col-md-offset-3
    table.table
      thead
        tr
          th 名前
          th
          - if session[:is_login]
            th
            th

      tbody
        - @members.each do |member|
          tr
            td = member.name
            - if session[:is_login]
              td = link_to '修正', edit_member_path(member), method: :get, class:"btn btn-info"
              td = link_to '削除', member, method: :delete, class:"btn btn-danger"

    br

app/views/members/new.html.slim
div.row
  div.col-md-6.col-md-offset-3
    h1 新しいメンバーの追加

    == render 'form'

app/views/members/show.html.slim
div.row
  div.col-md-6.col-md-offset-3
    div.text-center

      h3#notice = notice

      p
        h2
          strong Name:
          = @member.name
        => link_to 'Edit', edit_member_path(@member), class:"btn btn-info"
        '|
        = link_to '新しいメンバーを作る', new_member_path, class:"btn btn-success"
        '|
        =< link_to 'Back', members_path, class:"btn btn-info"